spring.application.name=metaMapa
# src/main/resources/application.properties
# URLs de los servicios (ajustar host/puerto según tu entorno)
metamapa.dinamica.url=http://localhost:8080/din
metamapa.estatica.url=http://localhost:8080/esta
metamapa.proxy.url=http://localhost:8080/api
metamapa.agregacion.url=http://localhost:8080/agre
metamapa.estadistica.url=http://localhost:8080/estad


# Puerto de la app (opcional)
server.port=8085

