spring.application.name=metaMapa
# src/main/resources/application.properties
# URLs de los servicios (ajustar host/puerto según tu entorno)
auth.service.url=http://localhost:8081
metamapa.service.url=http://localhost:8082

# Puerto de la app (opcional)
server.port=8085

