# src/main/resources/application.properties
spring.application.name=metaMapa

# URLs de los servicios (ajustar host/puerto según tu entorno)
metamapa.dinamica.url=http://54.232.5.23:8080/din
metamapa.estatica.url=http://54.232.5.23:8080/esta
metamapa.proxy.url=http://54.232.5.23:8080/api
metamapa.agregacion.url=http://54.232.5.23:8080/agre
metamapa.estadistica.url=http://54.232.5.23:8080/estadisticas

metamapa.estatica.forward-url=http://54.232.5.23:8080/agre/priv/hechos/estatica

# Token/header privados usados para llamadas admin (se inyectan en la vista como valores ocultos)
metamapa.priv.token=GRUPO-28
metamapa.priv.header=X-ADMIN-TOKEN

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mvc.hiddenmethod.filter.enabled=true

# Puerto de la app (opcional)
server.port=8085
